### ISSUE TITLE
Initialization between (-2, 2) failed after 100 attempts.

### ISSUE THREAD

**Issue by tommylees112** [Torvaney/soccerstan#3]
When running the 'dixon-coles' model I kept get the following error messages:

`ipython src/soccerstan.py 'data/example.csv' 'dixon-coles'`

```
Initialization between (-2, 2) failed after 100 attempts.
 Try specifying initial values, reducing ranges of constrained values, or reparameterizing the model.

Rejecting initial value:
  Log probability evaluates to log(0), i.e. negative infinity.
  Stan can't start sampling from this initial value.
```

Which culminates after sampling to:
```
"""
Traceback (most recent call last):
  File "/Users/TommyLees/anaconda3/envs/bayes/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/TommyLees/anaconda3/envs/bayes/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "stanfit4anon_model_ef4241d02b98103bce15111cba0d26cc_4742302921487914763.pyx", line 370, in stanfit4anon_model_ef4241d02b98103bce15111cba0d26cc_4742302921487914763._call_sampler_star
  File "stanfit4anon_model_ef4241d02b98103bce15111cba0d26cc_4742302921487914763.pyx", line 403, in stanfit4anon_model_ef4241d02b98103bce15111cba0d26cc_4742302921487914763._call_sampler
RuntimeError: Initialization failed.
"""

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
~/Desktop/football_modelling/soccerstan/src/soccerstan.py in <module>()
    210         True,# args.cache,
    211         iter=args.iter,    # compiled into **kwargs
--> 212         chains=args.chains #
    213     )
    214

~/Desktop/football_modelling/soccerstan/src/soccerstan.py in fit_model(data, team_map, model, use_cache, **kwargs)
     87     }
     88     # sample the model
---> 89     fit = stan_model.sampling(data=model_data, **kwargs)
     90     output = fit.extract()
     91     # odict_keys(['home_advantage', 'offense_raw', 'defense_raw',

~/anaconda3/envs/bayes/lib/python3.6/site-packages/pystan/model.py in sampling(self, data, pars, chains, iter, warmup, thin, seed, init, sample_file, diagnostic_file, verbose, algorithm, control, n_jobs, **kwargs)
    724         call_sampler_args = izip(itertools.repeat(data), args_list, itertools.repeat(pars))
    725         call_sampler_star = self.module._call_sampler_star
--> 726         ret_and_samples = _map_parallel(call_sampler_star, call_sampler_args, n_jobs)
    727         samples = [smpl for _, smpl in ret_and_samples]
    728

~/anaconda3/envs/bayes/lib/python3.6/site-packages/pystan/model.py in _map_parallel(function, args, n_jobs)
     79         try:
     80             pool = multiprocessing.Pool(processes=n_jobs)
---> 81             map_result = pool.map(function, args)
     82         finally:
     83             pool.close()

~/anaconda3/envs/bayes/lib/python3.6/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267
    268     def starmap(self, func, iterable, chunksize=None):

~/anaconda3/envs/bayes/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645
    646     def _set(self, i, obj):

RuntimeError: Initialization failed.
```

I have tried looking at the Stan Discourse and will post there if necessary but have you come across this error before?

Tommy

**Comment by Torvaney** [comment]
Hi Tommy,

Thanks for getting in touch. I think there are some real issues with how the Dixon-Coles model is specified here. There's a similar issue flagged #1.

It's on my to-do to look into it but I haven't had the time recently unfortunately.

**Comment by tommylees112** [comment]
Hi Ben

What's your background / what do you do now? I think these models are
really cool - I'm a PhD student looking at droughts in East Africa. Would
love to help out if I knew how I could be helpful because this is a beaut
package - really impressed.

Do you mind if I use this to write some blog posts about football
modelling??

**Comment by Torvaney** [comment]
Hi Tommy,

Thanks for your interest. I'm currently a Data Scientist at [Wefarm](https://wefarm.org/), so geographically related to your work at the least:). If you're interested in chatting more, feel free to send me an email at torvaney [at] protonmail.com

As for the project, any thoughts, feedback (it's fine to make new issues for feedback or feature requests) or contributions (bug-fixes, project structure improvements, new models, etc...) would be amazing. One model I was interested in adding was [Dixon and Robinson](http://wwwf.imperial.ac.uk/~ejm/M3S4/Problems/football.pdf), but I struggled to work out how best to implement it here.

Happy for you to use soccerstan for anything you like. If you're interested in using Dixon-Coles specifically, you might be interested in the [regista](https://github.com/Torvaney/regista) R package. It does Dixon-Coles better and is better documented (see package docs and links at the bottom of the readme) than soccerstan.

Hope that helps

**Comment by LukasNeugebauer** [comment]
Hey Ben and Tommy,
I know this is an old issue but I ran into the same problem. The problem seems to have been that the constraint on rho wasn't enforced. Have a look at my pull request, if that fixes the issue!
Best,
Lukas

**Comment by Torvaney** [comment]
Thanks, Lukas! The PR looks great. I have merged it in
